agent:
  model:
    name: "deepseek/deepseek-reasoner"
    api_key: "sk-358445ab6cd748c8965a44540397f9ed"
    temperature: 0
    per_instance_cost_limit: 2.0
  tools:
    env_variables:
      PYTHONDONTWRITEBYTECODE: "1"
    parse_function: 
      type: "thought_action"
    enable_bash_tool: true
    bundles:
      - path: tools/submit
env:
  deployment:
    image: "python:3.11"
  repo:
    path: "/home/isodin/Documents/Course Work/gok"
  post_startup_commands:
    - "git config --global user.name 'SWE-agent@ai.com' && git config --global user.email 'SWE-agent'"
actions:
  apply_patch_locally: true


problem_statement:
  #text: "Create REST API server on Golang with only one endpoint for healthcheck. Use 'echo' package."
  path: "/home/isodin/Documents/Course Work/problem.md"